"use client";

import Link from "next/link";
import Image from "next/image";
import { useCart } from "@/contexts/CartContext";
import { useLanguage } from "@/contexts/LanguageContext";

const FALLBACK =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";

  export default function CartPage() {
    const { items, removeItem, updateQuantity, totalPrice } = useCart();
      const { t, dir } = useLanguage();

        if (items.length === 0) {
            return (
                  <main dir={dir} className="w-full bg-white min-h-[60vh] flex flex-col items-center justify-center px-4 text-center">
                          <p className="text-2xl mb-4">🛍️</p>
                                  <h1 className="text-xl font-black text-gray-800 mb-2">{t("cart_empty_title")}</h1>
                                          <p className="text-gray-400 mb-8">{t("cart_empty_desc")}</p>
                                                  <Link
                                                            href="/"
                                                                      className="bg-[#d4637d] text-white px-10 py-3 rounded-full font-bold shadow-lg hover:bg-[#b84d65] transition-all"
                                                                              >
                                                                                        {t("browse_products")}
                                                                                                </Link>
                                                                                                      </main>
                                                                                                          );
                                                                                                            }

                                                                                                              return (
                                                                                                                  <main dir={dir} className="w-full bg-white min-h-[60vh] pb-32">
                                                                                                                        <div className="max-w-3xl mx-auto px-4 py-10">
                                                                                                                                <h1 className="text-2xl font-black text-gray-800 mb-8">{t("cart_title")}</h1>

                                                                                                                                        <div className="flex flex-col gap-4">
                                                                                                                                                  {items.map((item) => (
                                                                                                                                                              <div
                                                                                                                                                                            key={item.id}
                                                                                                                                                                                          className="flex items-center gap-4 bg-white border border-gray-100 rounded-2xl p-4 shadow-sm"
                                                                                                                                                                                                      >
                                                                                                                                                                                                                    <div className="relative w-20 h-20 rounded-xl overflow-hidden bg-gray-50 flex-shrink-0">
                                                                                                                                                                                                                                    <Image src={item.image_url || FALLBACK} alt={item.name} fill className="object-cover" />
                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                <div className="flex-1 text-right">
                                                                                                                                                                                                                                                                                <h3 className="font-bold text-gray-800 mb-1">{item.name}</h3>
                                                                                                                                                                                                                                                                                                <p className="text-[#d4637d] font-black">{item.price} {t("currency")}</p>
                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-3 bg-gray-50 rounded-full px-3 py-1.5">
                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                              onClick={() => updateQuantity(item.id, item.quantity + 1)}
                                                                                                                                                                                                                                                                                                                                                                                className="w-7 h-7 flex items-center justify-center text-lg font-bold text-gray-600 hover:text-[#d4637d]"
                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="font-bold text-gray-800 w-4 text-center">{item.quantity}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => updateQuantity(item.id, item.quantity - 1)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-7 h-7 flex items-center justify-center text-lg font-bold text-gray-600 hover:text-[#d4637d]"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        −
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => removeItem(item.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="text-gray-300 hover:text-red-500 transition-colors flex-shrink-0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    aria-label="حذف"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <path d="M6 6l12 12M6 18L18 6" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-8 bg-gray-50 rounded-2xl p-6 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-lg font-bold text-gray-700">{t("total")}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="text-2xl font-black text-[#d4637d]">{totalPrice} {t("currency")}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href="/checkout"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="mt-6 block w-full text-center bg-[#d4637d] text-white py-4 rounded-full font-black text-lg shadow-xl hover:bg-[#b84d65] transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {t("checkout_btn")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }