"use client";

import { useState } from "react";
import Image from "next/image";
import { Category, Product } from "@/lib/types";
import AddToCartButton from "@/components/AddToCartButton";
import { useLanguage } from "@/contexts/LanguageContext";

const FALLBACK = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";

export default function ProductsContent({
  products,
    categories,
    }: {
      products: Product[];
        categories: Category[];
        }) {
          const { t, language, dir } = useLanguage();
            const [activeCategory, setActiveCategory] = useState<string>("all");

              const img = (url: string | undefined) => (url && url !== "" ? url : FALLBACK);
                const catName = (cat: Category) => (language === "en" && cat.name_en ? cat.name_en : cat.name);
                  const prodName = (p: Product) => (language === "en" && p.name_en ? p.name_en : p.name);

                    const filtered =
                        activeCategory === "all" ? products : products.filter((p) => p.category_id === activeCategory);

                          return (
                              <main dir={dir} className="w-full bg-white pb-32">
                                    <div className="max-w-7xl mx-auto px-4 py-10">
                                            <h1 className="text-3xl font-black text-gray-800 mb-8">{t("all_products")}</h1>

                                                    {/* تبويبات التصنيفات */}
                                                            <div className="flex gap-3 overflow-x-auto no-scrollbar mb-10 pb-2">
                                                                      <button
                                                                                  onClick={() => setActiveCategory("all")}
                                                                                              className={`flex-shrink-0 px-6 py-2.5 rounded-full text-sm font-bold border-2 transition-all ${
                                                                                                            activeCategory === "all"
                                                                                                                            ? "border-[#d4637d] bg-[#fff5f8] text-[#d4637d]"
                                                                                                                                            : "border-gray-200 text-gray-500"
                                                                                                                                                        }`}
                                                                                                                                                                  >
                                                                                                                                                                              {t("filter_all")}
                                                                                                                                                                                        </button>
                                                                                                                                                                                                  {categories.map((cat) => (
                                                                                                                                                                                                              <button
                                                                                                                                                                                                                            key={cat.id}
                                                                                                                                                                                                                                          onClick={() => setActiveCategory(cat.id)}
                                                                                                                                                                                                                                                        className={`flex-shrink-0 px-6 py-2.5 rounded-full text-sm font-bold border-2 transition-all ${
                                                                                                                                                                                                                                                                        activeCategory === cat.id
                                                                                                                                                                                                                                                                                          ? "border-[#d4637d] bg-[#fff5f8] text-[#d4637d]"
                                                                                                                                                                                                                                                                                                            : "border-gray-200 text-gray-500"
                                                                                                                                                                                                                                                                                                                          }`}
                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                    {catName(cat)}
                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                          {/* شبكة المنتجات */}
                                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-2 md:grid-cols-4 gap-6 md:gap-10">
                                                                                                                                                                                                                                                                                                                                                                                                            {filtered.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={item.id} className="bg-white rounded-[2.5rem] overflow-hidden shadow-sm border border-gray-50 group hover:shadow-xl transition-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="h-64 relative overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Image src={img(item.image_url)} alt={prodName(item)} fill sizes="(max-width: 768px) 50vw, 25vw" className="object-cover group-hover:scale-110 transition-transform duration-700" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.discount_price && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="absolute top-5 right-5 bg-red-500 text-white text-[10px] font-black px-3 py-1 rounded-full">{t("discount_badge")}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {item.is_new && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="absolute top-5 left-5 bg-blue-500 text-white text-[10px] font-black px-3 py-1 rounded-full">{t("new_badge")}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {item.is_featured && !item.is_new && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="absolute top-5 left-5 bg-amber-500 text-white text-[10px] font-black px-3 py-1 rounded-full">{t("bestseller_badge")}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-6 text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="font-bold text-gray-800 mb-3 truncate text-lg">{prodName(item)}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center justify-start gap-3 flex-row-reverse mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {item.discount_price ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-[#d4637d] font-black text-xl">{item.discount_price} {t("currency")}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-gray-300 line-through text-xs font-medium">{item.price} {t("currency")}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-gray-800 font-black text-xl">{item.price} {t("currency")}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AddToCartButton
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name={prodName(item)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            price={item.discount_price || item.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              image_url={item.image_url}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {filtered.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center text-gray-400 py-20">{t("no_results")}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }